### ISSUE TITLE
Having trouble with turning my PNG image into 4 bin files (because I'm stupid)

### ISSUE THREAD

**Issue by Seii-FPV** [EVilm1/WIKI-HACK-DJI-OSD#2]
Hello,

First of all, thank you for all your effort you're putting into this. I've created a PNG image (following instructions, but it's also quite similar to what I used to do for Betaflight analog fonts and some digital ones for Walksnail Avatar).

I've never dealt with Python, and I feel super lost. I am trying to turn my PNG image into those 4 bin files so I can use it with my Dji goggles v2 with WTFOS installed.

I've installed the latest Python package, and ever the one from Microsoft store... nothing works when I try to execute this line:

`python3 template2img.py [NameOfYourImage].png`

I am trying to execute that command from PowerSheel, while in the mcm2img-templates folder.

...and all I get is this:

> File "C:\Users\seiis\Desktop\mcm2img-templates\mcm2img-templates\template2img.py", line 2, in <module>
>     from PIL import Image
> ModuleNotFoundError: No module named 'PIL'

I would so appreciate if you could help me understand how to turn my PNG into bin files. I am totally lost :(

Thank you so much in advance!
Seii

**Comment by Seii-FPV** [comment]
I am so sorry, I believe I just had to install Pillow before executing this command. I actually managed to export 2 bin files and 4 PNG images (like vertical sprite sheets I used to use when making Walksnail Avatar fonts).

I hope I did it correctly :)

**Comment by EVilm1** [comment]
No problem, I'm happy that it works for you! 💪
Don't hesitate if you have any other problems.

**Comment by Seii-FPV** [comment]
> No problem, I'm happy that it works for you! 💪 Don't hesitate if you have any other problems.

Thank you so much my friend! I do have another quick question, and was hoping you could suggest something... I've finally completed my Walksnail Avatar font, as well as exactly the same version for WTFOS (Dji goggles). What would be the best thing to do if I want to make it public, where to upload? Is there any way to have it available for public, but with maybe some kind of download counter on a page (simply to see the number of downloads and interest)? I am no coder, I mostly do graphics, video editing, animations, etc. Here is my last YT flight session where you can see my font and some icons (not all are on the screen, but I went through every single icon slot in that template file and made sure all looks clean and ready for publishing. This is Walksnail Avatar: https://www.youtube.com/watch?v=GKzdnVUamFY , and this is almost the same version, but for WTFOS: https://www.youtube.com/watch?v=7usDRMEzYZs (I just made it for my friend, she flies drones too, and her request was to be pink :)

**Comment by EVilm1** [comment]
Hi! Glad it worked out for you. Cool videos! If you want to share your fonts the best solution for me would be to share them on GITHUB exactly like I do.
You'll put your github link in your youtube video for example. 
Then you also have statistics and insights in your github page that you own.
I hope this helps ;)

**Comment by Seii-FPV** [comment]
Thank you so much once again! I will upload it on Github, I just wasn't aware that you can see stats (downloads etc) there. People ask me about the font and if it's available somewhere and I did not know what to tell them. Greatly appreciated!
